package DadosRol;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.ImageIcon;

/**
 *
 * @author alegur
 */
public class Dados extends javax.swing.JFrame {

    /**
     * Creates new form DadosRol
     */
    public Dados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCambiardado = new javax.swing.JComboBox<>();
        jLimagen = new javax.swing.JLabel();
        jLtitulo = new javax.swing.JLabel();
        jLresult = new javax.swing.JLabel();
        jBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCambiardado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jCambiardado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Dado de 6", "Dado de 8", "Dado de 10", "Dado de 12", "Dado de 20" }));
        jCambiardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCambiardadoActionPerformed(evt);
            }
        });
        jCambiardado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCambiardadoPropertyChange(evt);
            }
        });

        jLtitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLtitulo.setText("SELECCIONA UN DADO");

        jLresult.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLresult.setText("NUMERO");

        jBoton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jBoton.setText("ACEPTAR");
        jBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(jCambiardado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(53, 53, 53)
                                                                .addComponent(jBoton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jLresult, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(62, 62, 62))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(6, 6, 6)
                                .addComponent(jLimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jCambiardado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLresult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jBoton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCambiardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCambiardadoActionPerformed
        // TODO add your handling code here:
        ImageIcon op0=new ImageIcon("./src/media/elegir.png");
        ImageIcon op1=new ImageIcon("./src/media/d6.gif");
        ImageIcon op2=new ImageIcon("./src/media/d8.png");
        ImageIcon op3=new ImageIcon("./src/media/d10.png");
        ImageIcon op4=new ImageIcon("./src/media/d12.png");
        ImageIcon op5=new ImageIcon("./src/media/d20.gif");

        if(jCambiardado.getSelectedItem().toString().equals("Elegir")){
            jLimagen.setIcon(op0);
        }else if(jCambiardado.getSelectedItem().equals("Dado de 6")){
            jLimagen.setIcon(op1);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 8")){
            jLimagen.setIcon(op2);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 10")){
            jLimagen.setIcon(op3);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 12")){
            jLimagen.setIcon(op4);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 20")){
            jLimagen.setIcon(op5);
        }

    }//GEN-LAST:event_jCambiardadoActionPerformed

    private void jCambiardadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCambiardadoPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jCambiardadoPropertyChange

    private void jBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonActionPerformed
        // TODO add your handling code here:
        int val1=(int)(Math.random()*(6-1)+1);
        int val2=(int)(Math.random()*(8-1)+1);
        int val3=(int)(Math.random()*(10-1)+1);
        int val4=(int)(Math.random()*(12-1)+1);
        int val5=(int)(Math.random()*(20-1)+1);

        if(jCambiardado.getSelectedItem().toString().equals("Dado de 6")){
            jLresult.setText("Lado es "+val1);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 8")){
            jLresult.setText("Lado es "+val2);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 10")){
            jLresult.setText("Lado es "+val3);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 12")){
            jLresult.setText("Lado es "+val4);
        }else if(jCambiardado.getSelectedItem().toString().equals("Dado de 20")){
            jLresult.setText("Lado es "+val5);
        }
    }//GEN-LAST:event_jBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoton;
    private javax.swing.JComboBox<String> jCambiardado;
    private javax.swing.JLabel jLimagen;
    private javax.swing.JLabel jLresult;
    private javax.swing.JLabel jLtitulo;
    // End of variables declaration//GEN-END:variables
}
